# Generated by Django 3.1.5 on 2021-01-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('dependency_software', models.ManyToManyField(related_name='_software_dependency_software_+', to='software.Software')),
            ],
        ),
    ]
