# Generated by Django 3.1.5 on 2021-01-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='dependency_software',
            field=models.ManyToManyField(to='software.Software'),
        ),
    ]
