# Generated by Django 3.1.5 on 2021-01-27 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_application.category')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_author', to=settings.AUTH_USER_MODEL)),
                ('categorys', models.ManyToManyField(to='core_application.Category')),
                ('required_users', models.ManyToManyField(related_name='setting_required', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
