# Generated by Django 3.1.5 on 2021-01-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='mother',
            new_name='parent',
        ),
    ]
