# Generated by Django 3.1.5 on 2021-02-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0004_changehistoryentry_requirementgroup_usercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementgroup',
            old_name='software',
            new_name='software_list',
        ),
        migrations.AddField(
            model_name='requirementgroup',
            name='change_history',
            field=models.ManyToManyField(to='core_application.ChangeHistoryEntry'),
        ),
    ]
