# Generated by Django 3.1.5 on 2021-01-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinformation',
            name='socket_id',
            field=models.CharField(default=None, max_length=30, verbose_name='socket_id'),
            preserve_default=False,
        ),
    ]
