# Generated by Django 3.1.5 on 2021-02-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRuleDto',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('validation.validationrule',),
        ),
    ]
